// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndrxhyrjjybnsohxykbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kcnhoeXJqanlibnNvaHh5a2JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTUwNDUsImV4cCI6MjA2NjM3MTA0NX0.4-Vnbjv4EzCs38O8GrcqqiPrU4_trJEP-n463jwoqZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);